/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterTrustBundleSelectorApplyConfiguration represents a declarative configuration of the ClusterTrustBundleSelector type for use
// with apply.
//
// clusterTrustBundleSelector allows to configure trust by poiting to
// a selection of ClusterTrustBundles
type ClusterTrustBundleSelectorApplyConfiguration struct {
	// name selects a single ClusterTrustBundle by name.
	//
	// Mutually-exclusive with `signerName` and `labelSelector`.
	Name *string `json:"name,omitempty"`
	// signerName selects all ClusterTrustBundles for a signer with
	// matching name.
	// The selection can be narrowed down by using `labelSelector`.
	// The contents of all selected ClusterTrustBundles will be
	// unified and deduplicated.
	//
	// Mutually-exclusive with `name`.
	SignerName *string `json:"signerName,omitempty"`
	// labelSelector allows to narrow down the selection of
	// ClusterTrustBundles for a signer with a given `signerName`.
	// If unset, interpreted as "match nothing". If set but empty,
	// interpreted as "match everything".
	//
	// Mutually-exclusive with `name`.
	LabelSelector *metav1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
}

// ClusterTrustBundleSelectorApplyConfiguration constructs a declarative configuration of the ClusterTrustBundleSelector type for use with
// apply.
func ClusterTrustBundleSelector() *ClusterTrustBundleSelectorApplyConfiguration {
	return &ClusterTrustBundleSelectorApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterTrustBundleSelectorApplyConfiguration) WithName(value string) *ClusterTrustBundleSelectorApplyConfiguration {
	b.Name = &value
	return b
}

// WithSignerName sets the SignerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SignerName field is set to the value of the last call.
func (b *ClusterTrustBundleSelectorApplyConfiguration) WithSignerName(value string) *ClusterTrustBundleSelectorApplyConfiguration {
	b.SignerName = &value
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *ClusterTrustBundleSelectorApplyConfiguration) WithLabelSelector(value *metav1.LabelSelectorApplyConfiguration) *ClusterTrustBundleSelectorApplyConfiguration {
	b.LabelSelector = value
	return b
}
